name: Build PDF and Upload to SharePoint

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Subfolder in SharePoint (if not exists)
        env:
          SHAREPOINT_SITE: ${{ secrets.SHAREPOINT_SITE }}
          SHAREPOINT_DOC_LIB: ${{ secrets.SHAREPOINT_DOC_LIB }}
          SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
          SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
        run: |
          # Attempt to create the folder using a POST request.
          # Note: This might return an error if the folder already exists; you can choose to ignore it.
          curl --fail --ntlm --user "$SHAREPOINT_USERNAME:$SHAREPOINT_PASSWORD" \
            -H "Accept: application/json;odata=verbose" \
            -H "Content-Type: application/json;odata=verbose" \
            -d "{\"__metadata\": {\"type\": \"SP.Folder\"}, \"ServerRelativeUrl\": \"$SHAREPOINT_DOC_LIB\"}" \
            "$SHAREPOINT_SITE/_api/web/folders" || echo "Folder may already exist or creation failed"
     
      # - name: Verify Folder Exists in SharePoint
      #   env:
      #     SHAREPOINT_SITE: ${{ secrets.SHAREPOINT_SITE }}
      #     SHAREPOINT_DOC_LIB: ${{ secrets.SHAREPOINT_DOC_LIB }}
      #     SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
      #     SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
      #   run: |
      #     echo "Checking if folder $SHAREPOINT_DOC_LIB exists..."
      #     curl --fail --ntlm --user "$SHAREPOINT_USERNAME:$SHAREPOINT_PASSWORD" \
      #       "$SHAREPOINT_SITE/_api/web/GetFolderByServerRelativeUrl('$SHAREPOINT_DOC_LIB')"
      #     echo "Folder exists."

      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Build PDF from Markdown
        run: |
          chmod +x .github/scripts/build-pdf.sh
          .github/scripts/build-pdf.sh

      - name: List Workspace Files
        run: ls -la
  
      - name: Upload PDF to SharePoint
        env:
          SHAREPOINT_SITE: ${{ secrets.SHAREPOINT_SITE }}
          SHAREPOINT_DOC_LIB: ${{ secrets.SHAREPOINT_DOC_LIB }}
          SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
          SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
        run: |
          curl --fail --verbose --ntlm --user "$SHAREPOINT_USERNAME:$SHAREPOINT_PASSWORD" \
            -T output.pdf \
            "$SHAREPOINT_SITE/_api/web/GetFolderByServerRelativeUrl('$SHAREPOINT_DOC_LIB')/Files/add(url='output.pdf',overwrite=true)"
