name: Build PDF and Upload to SharePoint

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get SharePoint Access Token
        id: get_token
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          TOKEN_RESPONSE=$(curl -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default" \
            https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token)
          echo "Token Response: $TOKEN_RESPONSE"
          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')
          if [ "$ACCESS_TOKEN" = "null" ] || [ -z "$ACCESS_TOKEN" ]; then
            echo "Failed to retrieve access token"
            exit 1
          fi
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      # -d "grant_type=client_credentials&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&scope=https://tynesidetech.sharepoint.com/.default" \

      - name: Test Graph Auth
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
        run: |
          curl --fail --verbose \
          -X GET \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          'https://graph.microsoft.com/v1.0/users'
      
      - name: Test Access Token by Getting Site Info
        env:
          SHAREPOINT_SITE: ${{ secrets.SHAREPOINT_SITE }}
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
        run: |
          curl --fail --verbose \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Accept: application/json;odata=verbose" \
            "$SHAREPOINT_SITE/_api/web"
      
      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Build PDF from Markdown
        run: |
          chmod +x .github/scripts/build-pdf.sh
          .github/scripts/build-pdf.sh
      
      - name: Upload PDF to SharePoint
        env:
          SHAREPOINT_SITE: ${{ secrets.SHAREPOINT_SITE }}  # e.g., "https://{companyName}.sharepoint.com/sites/{Section}"
          SHAREPOINT_DOC_LIB: ${{ secrets.SHAREPOINT_DOC_LIB }}  # e.g., "/Shared Documents"
        run: |
          curl --fail --request POST \
            --header "Authorization: Bearer $ACCESS_TOKEN" \
            --header "Accept: application/json;odata=verbose" \
            --header "Content-Type: application/json;odata=verbose" \
            --data-binary @output.pdf \
            "$SHAREPOINT_SITE/_api/web/GetFolderByServerRelativeUrl('$SHAREPOINT_DOC_LIB')/Files/add(url='output.pdf',overwrite=true)"
