name: Build PDF and Upload to SharePoint

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Build PDF from Markdown
        run: |
          chmod +x build_pdf.sh
          ./build_pdf.sh

      - name: Upload PDF to SharePoint
        env:
          SHAREPOINT_SITE: ${{ secrets.SHAREPOINT_SITE }}
          SHAREPOINT_DOC_LIB: ${{ secrets.SHAREPOINT_DOC_LIB }}
          SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
          SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
        run: |
          # Replace the URL path as needed for your SharePoint configuration.
          curl --ntlm --user "$SHAREPOINT_USERNAME:$SHAREPOINT_PASSWORD" \
          -T output.pdf \
          "$SHAREPOINT_SITE/_api/web/GetFolderByServerRelativeUrl('$SHAREPOINT_DOC_LIB')/Files/add(url='output.pdf',overwrite=true)"
